[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RGCR_lite"
version = "0.1.0"
authors = [
    { name = "Avital Zar", email = "tchykzr@gmail.com" }
]
description = "An easier for use version of the RGCR method presented in https://arxiv.org/abs/1806.05085"
readme = "README.md"

dependencies = [
	"pref_voting @ git+https://github.com/AvitalZar/pref_voting.git"
]

[tool.setuptools]
packages = { find = {} }